### ISSUE TITLE
Possible issue of undefined variable

### ISSUE THREAD

**Issue by yanrpi** [jaxony/unet-pytorch#1]
https://github.com/jaxony/unet-pytorch/blob/0d1a68ae897a4d7087d080e442e403b829a4c289/model.py#L177

At line 177, "outs" is undefined for the first run. Should the order lines 177 and 178 be switched?

**Comment by jaxony** [comment]
Hi @yanrpi, thanks for brining this to my attention. I've actually found some other bugs. I will update the repo today or tomorrow with fixes.

**Comment by yanrpi** [comment]
Thanks for sharing your codes!

**Comment by jaxony** [comment]
@yanrpi I just added fixes to `model.py` in issue #2 . Let me know if there are any problems still.

**Comment by yanrpi** [comment]
Great, thanks!

**Comment by CharlesLaroche** [comment]
Hi, 
Sorry to re-open this issue 2 years later but the problem may not be fixed and is now line 184 : https://github.com/jaxony/unet-pytorch/blob/2bb0e44a2d5c7c04b589d5d942673aee52bcff58/model.py#L184
Thanks a lot for the code !
